doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'App\Infrastructure\Doctrine\Migrations': '%kernel.project_dir%/src/Infrastructure/Doctrine/Migrations'
    enable_profiler: false

    storage:
        table_storage:
            table_name: 'migration'

    organize_migrations: 'BY_YEAR_AND_MONTH'
