parameters:
    telegram_bot_token_fordim: '%env(TELEGRAM_BOT_TOKEN_FORDIM)%'
    telegram_bot_token_marriage: '%env(TELEGRAM_BOT_TOKEN_MARRIAGE)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude:
            - '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
            - '../src/Infrastructure/Doctrine/{Entity,Type,Migrations}/*.php'
            - '../src/Infrastructure/Doctrine/Migrations/**/*.php'
            - '../src/Domain/**/{Exception,Traits,Entity,Event,EventHandler}/'
            - '../src/Domain/**/{Exception,Traits,Entity,Event,EventHandler}/*.php'
            - '../src/Domain/**/{Exception,Traits,Entity,Event,EventHandler}/**/*.php'
            - '../src/Domain/**/Aggregate/**/*.php'

    App\Controller\:
        resource: '../src/Controller'
        exclude:
            - '../src/Controller/**/**/**/*Response.php'
            - '../src/Controller/**/**/**/*Request.php'
        tags: [ 'controller.service_arguments' ]

    app.telegram.fordim.api:
        class: Telegram\Bot\Api
        arguments:
            - '%telegram_bot_token_fordim%'

    App\Controller\Api\Telegram\Fordim\TelegramController:
        arguments:
            $telegram: '@app.telegram.fordim.api'

    app.telegram.marriage.api:
        class: Telegram\Bot\Api
        arguments:
            - '%telegram_bot_token_marriage%'

    App\Controller\Api\Telegram\Marriage\TelegramController:
        arguments:
            $telegram: '@app.telegram.marriage.api'

    App\Domain\Telegram\Command\Telegram\Marriage\CallbackQueryCommand:
        tags:
            - { name: 'telegram.command', command: 'callback_query' }
