parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude:
            - '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
            - '../src/Infrastructure/Doctrine/{Entity,Type,Migrations}/*.php'
            - '../src/Infrastructure/Doctrine/Migrations/**/*.php'
            - '../src/Domain/**/{Exception,Traits,Entity,Event,EventHandler}/'
            - '../src/Domain/**/{Exception,Traits,Entity,Event,EventHandler}/*.php'
            - '../src/Domain/**/{Exception,Traits,Entity,Event,EventHandler}/**/*.php'
            - '../src/Domain/**/Aggregate/**/*.php'

    App\Controller\:
        resource: '../src/Controller'
        exclude:
            - '../src/Controller/**/**/**/*Response.php'
            - '../src/Controller/**/**/**/*Request.php'
        tags: [ 'controller.service_arguments' ]
